//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyWebform.Pages
{


    public partial class RegisterMemberProgram
    {

        /// <summary>
        /// RegisterMembershipUserControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SurveyWebform.UserControls.RegisterMembershipUserControl RegisterMembershipUserControl;

        /// <summary>
        /// id_ButtonRegister control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button id_ButtonRegister;
    }
}
